[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
workdir = "backend"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/src/main"
healthcheckPath = "/health/live"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
